### ISSUE TITLE
Strange Email Received 

### ISSUE THREAD

**Issue by hygzhu** [Roland-Li/sona-checker#2]
Subject: Failed to check studies page. Cookie error?

# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_wlu-ls.sona-systems.com       FALSE   /       FALSE   0       WEBHOME 3FB92FABAD6AAC370E4CDADBF5A3CB10D0A6C7665AD890AEE5847CC466B120EA0247843D52DE4C818877765FDD5BCF298E4D7F096D33E3B1FFF00B3D5A405167394BD60ABEE0779ABB836BA54B469BD7E756E07C0F4140EFE0BA5C84D5EDFBC83FC6086FCEBED0373BC39EBF97C0311C5C4FCFE06E4DA8DD11470080F6FCE5B3

**Comment by Roland-Li** [comment]
This is a generic message sent out during login failures.

This specific break was due to the fact that Sona requires re-registering every term, thereby invalidating my bot's current login credentials. Subscribers to my personal host should stop receiving these emails shortly.
